# Generated by Django 3.0.8 on 2020-07-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Purchase',
        ),
    ]
